# Generated by Django 4.0.5 on 2022-06-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Напрямок')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL')),
                ('sort_number', models.DecimalField(decimal_places=0, max_digits=10, unique=True, verbose_name='Номер сортування')),
            ],
            options={
                'verbose_name': 'Напрямок',
                'verbose_name_plural': 'Напрямки',
                'ordering': ['sort_number'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Лікарь')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL')),
                ('education', models.TextField(blank=None, verbose_name='Освіта')),
                ('birthday', models.DateField(verbose_name='Дата народження')),
                ('description_of_experience', models.TextField(blank=None, verbose_name='Досвід опис')),
                ('years_of_experience', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Досвід років')),
                ('sort_number', models.DecimalField(decimal_places=0, max_digits=10, unique=True, verbose_name='Номер сортування')),
                ('directions', models.ManyToManyField(related_name='direction', to='doc_lists.direction')),
            ],
            options={
                'verbose_name': 'Лікар(я)',
                'verbose_name_plural': 'Лікарі',
                'ordering': ['sort_number'],
            },
        ),
    ]
